[project]
name = "utility-function-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.0.1",
    "mcp>=1.22.0",
    "python-dotenv>=1.2.1",
    "upstash-redis>=1.5.0",
]
